{% set name = "pannb" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pannb-{{ version }}.tar.gz
  sha256: 6cd1a7cfec1305136cafbc9953d2ba4288a05f4b565ec77bed226947e2a1ba6a

build:
  number: 0
  noarch: python
  entry_points:
    - pannb = pannb:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry >=1,<2
  run:
    - panflute >=2.1.3,<3.0.0
    - python >=3.8
  run_constrained:
    - pandoc >=2.15,<2.17
    - coloredlogs >=14,<16

test:
  imports:
    - pannb
  commands:
    - pip check
    - |
      echo '# testing' | pandoc -F pannb
  requires:
    - pip
    - pandoc >=2.15,<2.17

about:
  home: https://github.com/ickc/pannb/
  summary: pannb—pandoc filter for ipynb
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ickc.github.io/pannb/
  dev_url: https://github.com/ickc/pannb/issues/

extra:
  recipe-maintainers:
    - ickc
